/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* BeOS */
/* #undef BEOS */

/* Cygwin */
/* #undef CYGWIN */

/* HOME env.var exists */
#define HAVE_HOME 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Do we have midi support? */
#define HAVE_MIDI 1

/* Define to 1 if you have the <sstream> header file. */
#define HAVE_SSTREAM 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Linux */
#define LINUX 1

/* Mac OS X */
/* #undef MACOSX */

/* OpenBSD */
/* #undef OPENBSD */

/* Name of package */
#define PACKAGE "fitd"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "fitd"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "fitd 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "fitd"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* UNIX-variant */
#define UNIX 1

/* use precompiled header */
/* #undef USE_PRECOMPILED_HEADER */

/* Version number of package */
#define VERSION "0.1"

/* Windows */
/* #undef WIN32 */

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */
